services:
  yt-converter:
    build:
      context: .
      network: host
    container_name: yt-converter
    restart: unless-stopped
    ports:
      - "9999:9999"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache
      - ./cookies:/app/cookies  # not :ro, yt-dlp writes back to cookies
    environment:
      - COOKIES_FILE=/app/cookies/cookies.txt
    dns:
      - 8.8.8.8
      - 1.1.1.1
